import { Asset, Snapshot, blankAsset } from "./model";
const time = "2026-10-06T06:00:00.000Z";
export const demoPeople = [
  { name: "Nora Ellis", department: "Design" },
  { name: "Leo Hart", department: "Operations" },
  { name: "Maya Chen", department: "Finance" },
];
const rows = [
  [
    "DEMO-001",
    "MacBook Pro 14",
    "Laptop",
    "Apple",
    "MacBook Pro 14",
    "DEMO-C02X148",
    "16 GB / 512 GB",
    "Good",
    "Nora Ellis",
    "Locker",
    "Assigned",
    "Charger",
    "6499",
  ],
  [
    "DEMO-002",
    "Dell Latitude 5440",
    "Laptop",
    "Dell",
    "Latitude 5440",
    "DEMO-DL5440",
    "16 GB / 256 GB",
    "Good",
    "",
    "Engineering Area",
    "Available",
    "Charger",
    "3900",
  ],
  [
    "DEMO-003",
    "Dell UltraSharp 27",
    "Monitor",
    "Dell",
    "UltraSharp 27",
    "DEMO-MON27",
    "27 inch",
    "Good",
    "Leo Hart",
    "Engineering Area",
    "Assigned",
    "Power cable",
    "1800",
  ],
  [
    "DEMO-004",
    "iPad Air",
    "Tablet",
    "Apple",
    "iPad Air",
    "DEMO-IPAD01",
    "",
    "Unknown",
    "",
    "Engineering Area",
    "Needs review",
    "",
    "",
  ],
  [
    "DEMO-005",
    "Logitech MX Keys",
    "Peripheral",
    "Logitech",
    "MX Keys",
    "DEMO-MXKEYS",
    "Bluetooth",
    "Good",
    "Maya Chen",
    "Locker",
    "Assigned",
    "USB cable",
    "499",
  ],
  [
    "DEMO-006",
    "Lenovo ThinkPad T14",
    "Laptop",
    "Lenovo",
    "ThinkPad T14",
    "DEMO-T14",
    "16 GB / 512 GB",
    "Damaged",
    "",
    "Engineering Area",
    "Repair",
    "Charger",
    "4200",
  ],
  [
    "DEMO-007",
    "HP USB-C Dock",
    "Peripheral",
    "HP",
    "USB-C Dock",
    "DEMO-DOCK01",
    "USB-C",
    "Good",
    "",
    "Engineering Area",
    "Available",
    "Power adapter",
    "700",
  ],
];
export function fixtures(): Snapshot {
  const assets = rows.map(
    ([
      id,
      name,
      category,
      brand,
      model,
      serial,
      specs,
      condition,
      assignee,
      location,
      status,
      accessories,
      purchaseCost,
    ]) => ({
      ...blankAsset(),
      id,
      name,
      category,
      brand,
      model,
      serial,
      specs,
      condition,
      assignee,
      location,
      status,
      accessories,
      purchaseCost,
      serialChecked: true,
      specsChecked: !!specs,
      conditionChecked: condition !== "Unknown",
      version: 1,
      createdAt: time,
      updatedAt: time,
    }),
  ) as Asset[];
  return {
    assets,
    people: demoPeople,
    history: [
      {
        id: "demo-history-1",
        assetId: "DEMO-001",
        action: "Assign",
        actor: "Demo operator",
        at: "2026-10-05T09:30:00.000Z",
        from: {
          assignee: "",
          location: "Engineering Area",
          status: "Available",
        },
        to: {
          assignee: "Nora Ellis",
          location: "Locker",
          status: "Assigned",
        },
        notes: "Fictional assignment for preview.",
      },
      {
        id: "demo-history-2",
        assetId: "DEMO-001",
        action: "Created",
        actor: "Demo import",
        at: "2026-10-01T08:00:00.000Z",
        from: { assignee: "", location: "", status: "" },
        to: { assignee: "", location: "Engineering Area", status: "Available" },
        notes: "Fictional fixture.",
      },
    ],
  };
}
